### ISSUE TITLE
nodejs-8_x tries to hit the registry when building webpack

### ISSUE THREAD

**Issue by ixmatus** [adnelson/nixfromnpm#114]
Note that this package builds just fine with nodejs-6_x.

To reproduce:

```
$ nixfromnpm -p webpack -o ./testwebpack
...
Finished resolving webpack 3.11.0
Writing package file at /home/parnell/Development/oss/nixfromnpm/testwebpack/nodePackages/webpack/3.11.0.nix
Generating package definition object in /home/parnell/Development/oss/nixfromnpm/testwebpack/nodePackages/default.nix
Package webpack@>=0.0.0 built successfully.

$ nix-build --no-out-link --attr nodePackages.webpack ./testwebpack/default.nix
...
npm verb type system
npm verb stack FetchError: request to http://notaregistry.63272df60c-d-1.0.0.com/es5-ext failed, reason: getaddrinfo EBUSY notaregistry.63272df60c-d-1.0.0.com:80
npm verb stack     at ClientRequest.req.on.err (/nix/store/acmnpcywfv7wsijd5fxrm8z4y4ixdp47-nodejs-8.9.4/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)
npm verb stack     at emitOne (events.js:116:13)
npm verb stack     at ClientRequest.emit (events.js:211:7)
npm verb stack     at Socket.socketErrorListener (_http_client.js:387:9)
npm verb stack     at emitOne (events.js:116:13)
npm verb stack     at Socket.emit (events.js:211:7)
npm verb stack     at emitErrorNT (internal/streams/destroy.js:64:8)
npm verb stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
npm verb stack     at process._tickCallback (internal/process/next_tick.js:180:9)
npm verb cwd /tmp/nix-build-d-1.0.0-nodejs-8.9.4.drv-0/package
npm verb Linux 4.14.15
npm verb argv "/nix/store/acmnpcywfv7wsijd5fxrm8z4y4ixdp47-nodejs-8.9.4/bin/node" "/nix/store/acmnpcywfv7wsijd5fxrm8z4y4ixdp47-nodejs-8.9.4/bin/npm" "install" "." "--registry=http://notaregistry.63272df60c-d-1.0.0.com" "--fetch-retry-mintimeout=0" "--fetch-retry-maxtimeout=10" "--fetch-retries=0" "--userconfig=/dev/null" "--nodedir=/nix/store/mlycgcw8j8bwqjsazp7hr1axiqnwhc4y-node-sources" "--production" "--loglevel=verbose"
npm verb node v8.9.4
npm verb npm  v5.6.0
npm ERR! code EBUSY
npm ERR! errno EBUSY
npm ERR! request to http://notaregistry.63272df60c-d-1.0.0.com/es5-ext failed, reason: getaddrinfo EBUSY notaregistry.63272df60c-d-1.0.0.com:80
npm verb exit [ 1, true ]
```

**Comment by adnelson** [comment]
Interesting, it’s trying to get es5-ext, I guess that’s the problem. Does
the build succeed when using node 6?

**Comment by ixmatus** [comment]
Yes it does. I think I have this problem with the babel packages and `node-8_x` too.

**Comment by adnelson** [comment]
Hmm, well I’m not sure if it’s best to switch to node6 for the default
version; of course it can be changed by the user.

Alternatively if something funky is going on with npm specifically then
there might be another reason to use yarn

**Comment by ixmatus** [comment]
@adnelson oh yeah, I agree, we shouldn't change the default nodejs version. I think nodejs is behaving different with respect to what it considers a cached npm package or not.

I agree, IMHO the way forward is likely with yarn and not `npm` since it supports an `--offline` flag. I just wanted to create an issue ticket to track this since someone else might also run into it.

**Comment by adnelson** [comment]
Closing this as well due to #115 being merged. Reopen if necessary.
