### ISSUE TITLE
Fails for packages with circular dependencies

### ISSUE THREAD

**Issue by jb55** [adnelson/nixfromnpm#49]
try: http://npmrepo.com/es6-symbol

looks like npm attempts to shim the circular dependency and it's confusing the build script?

```
Creating shim for recursive dependency d@0.1.1
mkdir: created directory 'node_modules'
mkdir: created directory 'node_modules/d'
configuring
Creating shim for recursive dependency es5-ext@0.10.9
```

^ my best guess

subsequent error due to unfulfilled dep:

```
npm verb request uri http://notaregistry.12ec3aebac-d-0.1.1.derp/es5-ext
npm verb request no auth needed
npm info attempt registry request try #1 at 00:19:56
npm verb request id 79111b16d31781ea
npm http request GET http://notaregistry.12ec3aebac-d-0.1.1.derp/es5-ext
npm verb stack Error: getaddrinfo ENOTFOUND notaregistry.12ec3aebac-d-0.1.1.derp notaregistry.12ec3aebac-d-0.1.1.derp:80
npm verb stack     at errnoException (dns.js:26:10)
npm verb stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
npm verb cwd /tmp/nix-build-nodejs-5.1.1-d-0.1.1.drv-0/package
npm ERR! Linux 4.1.12
npm ERR! argv "/nix/store/wqsc6c7y910sfbjxv4850mqmd3gyk8q9-nodejs-5.1.1/bin/node" "/nix/store/wqsc6c7y910sfbjxv4850mqmd3gyk8q9-nodejs-5.1.1/bin/npm" "install" "." "--registry=http://notaregistry.12ec3aebac-d-0.1.1.derp" "--fetch-retry-mintimeout=0" "--fetch-retry-maxtimeout=10" "--fetch-retries=0" "--userconfig=/dev/null" "--nodedir=/nix/store/rfm6lwh715wnx434kkvh6j01nq9pas56-node-sources" "--production" "--loglevel=verbose"
npm ERR! node v5.1.1
npm ERR! npm  v3.3.12
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND notaregistry.12ec3aebac-d-0.1.1.derp notaregistry.12ec3aebac-d-0.1.1.derp:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/nix-build-nodejs-5.1.1-d-0.1.1.drv-0/package/npm-debug.log
builder for ‘/nix/store/d4gzj893338451fs2i8nwpn2bwws9jkm-nodejs-5.1.1-d-0.1.1.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/9zszxkgahqgs7k3p2n2fhmjl6g7g1v67-nodejs-5.1.1-es6-iterator-2.0.0.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/nhrlghc4yx90902xq0nans53blah5zsd-nodejs-5.1.1-es6-symbol-3.0.1.drv’: 1 dependencies couldn't be built
```

**Comment by adnelson** [comment]
Hey, sorry this languished for so long. I kind of took a break from this due to end-of-year crunch time.

So the shims approach was inherited from the `buildNodePackage` function in `nixpkgs` (see [here](https://github.com/NixOS/nixpkgs/blob/eaf10642093ba652d536f4b8fd9ba7526c69886a/pkgs/development/web/nodejs/build-node-package.nix), or a blog post on the topic [here](http://sandervanderburg.blogspot.com/2014/10/deploying-npm-packages-with-nix-package.html)). Theoretically, it *should* work just to create a directory in `node_packages` with a `package.json` file displaying the right name/version but I haven't really looked deeply into it. One thing that I'm planning to do is include a step in which we iterate through all of the dependencies and use `semver` to check if these dependencies are met -- unfortunately `npm` doesn't seem to provide this as a command on its own (which is why it's necessary to pass in a "fake registry" rather than just disabling registries altogether). Long story short, it's probably failing because the (fake) dependency it needs is not being created correctly, but I'm not totally sure.

**Comment by adnelson** [comment]
So I changed the shim dependency approach. Instead, now I'm just patching the `package.json` file to remove recursive dependencies. Hopefully this fixes this issue; if not, please reopen this.

**Comment by jb55** [comment]
sweet I'll try this again soon

**Comment by davidtwco** [comment]
@adnelson I've just ran into the same thing with the latest version of this repository when trying to install `gulp-cli`:

```
building
npm install --registry=http://notaregistry.58f9c5d7e1-for-own-0.1.3.com --fetch-retry-mintimeout=0 --fetch-retry-maxtimeout=10 --fetch-retries=0 --userconfig=/dev/null --nodedir=/nix/store/ajd2f2bfyc61vgkhvzrx6g3h7l913b4m-node-sources --production
npm verb type system
npm verb stack FetchError: request to http://notaregistry.6db7aeed11-es6-iterator-2.0.0.com/d failed, reason: getaddrinfo ENOTFOUND notaregistry.6db7aeed11-es6-iterator-2.0.0.com notaregistry.6db7aeed11-es6-iterator-2.0.0.com:80
npm verb stack     at ClientRequest.req.on.err (/nix/store/xq5x7v49zyb6lyg87cbv29p2szivkh2k-nodejs-9.11.1/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)
npm verb stack     at ClientRequest.emit (events.js:180:13)
npm verb stack     at Socket.socketErrorListener (_http_client.js:395:9)
npm verb stack     at Socket.emit (events.js:180:13)
npm verb stack     at emitErrorNT (internal/streams/destroy.js:64:8)
npm verb stack     at process._tickCallback (internal/process/next_tick.js:178:19)
npm verb cwd /tmp/nix-build-es6-iterator-2.0.0-nodejs-9.11.1.drv-0/package
npm verb Linux 4.16.10
npm verb argv "/nix/store/xq5x7v49zyb6lyg87cbv29p2szivkh2k-nodejs-9.11.1/bin/node" "/nix/store/xq5x7v49zyb6lyg87cbv29p2szivkh2k-nodejs-9.11.1/bin/npm" "install" "." "--registry=http://notaregistry.6db7aeed11-es6-iterator-2.0.0.com" "--fetch-retry-mintimeout=0" "--fetch-retry-maxtimeout=10" "--fetch-retries=0" "--userconfig=/dev/null" "--nodedir=/nix/store/ajd2f2bfyc61vgkhvzrx6g3h7l913b4m-node-sources" "--production" "--loglevel=verbose"
npm verb node v9.11.1
npm verb npm  v5.6.0
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to http://notaregistry.6db7aeed11-es6-iterator-2.0.0.com/d failed, reason: getaddrinfo ENOTFOUND notaregistry.6db7aeed11-es6-iterator-2.0.0.com notaregistry.6db7aeed11-es6-iterator-2.0.0.com:80
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm verb exit [ 1, true ]
```
