### ISSUE TITLE
crashes installing react-addons-create-fragment

### ISSUE THREAD

**Issue by gilligan** [adnelson/nixfromnpm#61]
I tried installing 
```
"react-addons-create-fragment": "0.14.5"
```
which results in npm crashing:
```
npm verb stack TypeError: Cannot read property 'react' of undefined
npm verb stack     at /nix/store/b3m14jf4swcazpcdhwmqsriv7kgw0k9c-nodejs-4.2.3/lib/node_modules/npm/lib/install.js:180:33
npm verb stack     at Array.forEach (native)
npm verb stack     at /nix/store/b3m14jf4swcazpcdhwmqsriv7kgw0k9c-nodejs-4.2.3/lib/node_modules/npm/lib/install.js:179:50
npm verb stack     at ReadFileContext.<anonymous> (/nix/store/b3m14jf4swcazpcdhwmqsriv7kgw0k9c-nodejs-4.2.3/lib/node_modules/npm/lib/install.js:368:22)
npm verb stack     at ReadFileContext.callback (/nix/store/b3m14jf4swcazpcdhwmqsriv7kgw0k9c-nodejs-4.2.3/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16)
npm verb stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
npm verb cwd /private/var/folders/l7/bqwl4z8s45l_tk_406_bwjm40000gn/T/nix-build-react-addons-create-fragment-0.14.5-nodejs-4.2.3.drv-0/package
npm ERR! Darwin 15.0.0
npm ERR! argv "/nix/store/b3m14jf4swcazpcdhwmqsriv7kgw0k9c-nodejs-4.2.3/bin/node" "/nix/store/b3m14jf4swcazpcdhwmqsriv7kgw0k9c-nodejs-4.2.3/bin/npm" "install" "." "--registry=http://notaregistry.4026ebd335-react-addons-create-fragment-0.14.5.derp" "--fetch-retry-mintimeout=0" "--fetch-retry-maxtimeout=10" "--fetch-retries=0" "--userconfig=/dev/null" "--nodedir=/nix/store/smbyyv33g5jyfpj9kzm5wk2zycxjnwmg-node-sources" "--production" "--loglevel=verbose"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7

npm ERR! Cannot read property 'react' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]
```

The full output is available here: https://gist.github.com/gilligan/61096990ea69b99ff41c

**Comment by gilligan** [comment]
Actually this works if I use `pkgs.nodejs-5_x`

**Comment by adnelson** [comment]
I'm not sure what's going on here, but it looks like a package-specific issue, not a `nixfromnpm` issue. There's no realistic way to guarantee that the expressions `nixfromnpm` generates will build correctly, with all of the possible things that could go wrong. Instead, it's designed to get you at least "mostly there", at which point you can apply whatever patches are necessary to get things to work, and have those changes stick.

I'm going to close this, but feel free to reopen it if there's something `nixfromnpm` should be doing that could fix this.

**Comment by gilligan** [comment]
Right, sorry for the noise ;)
